name: Upload-Artifacts

on:
  push:
    branches:
      - main

jobs:
  artifacts-push:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Get commit hash prefix for PR update
        env:
          COMMIT_SHA: ${{ github.sha }}
        run: |
          echo "SHORT_HASH=${COMMIT_SHA:0:7}" >> $GITHUB_ENV

      - run: cargo build -r

      - name: Authenticate with GCS
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.SA_GPS_ARTIFACTS_BUCKET_WRITER_ACCESS_KEY }}

      - name: Upload cairo_program_runner binary to GCP
        id: upload_cairo_program_runner
        uses: "google-github-actions/upload-cloud-storage@v2"
        with:
          path: "target/release/cairo_program_runner"
          destination: "cairo_program_runner_artifacts/${{ env.SHORT_HASH }}/release"

      - name: Upload stwo_vm_runner binary to GCP
        id: upload_stwo_vm_runner
        uses: "google-github-actions/upload-cloud-storage@v2"
        with:
          path: "target/release/stwo_vm_runner"
          destination: "stwo_vm_runner_artifacts/${{ env.SHORT_HASH }}/release"
